### ISSUE TITLE
Use deterministicGenerateK from secp256k1

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#10]
Hi.
Nonce generation per RFC6979 [was implemented in the secp256k1](https://github.com/bitcoin/secp256k1/pull/163) so [this JS function](https://github.com/wanderer/secp256k1-node/blob/master/index.js#L16) is no longer needed.

**Comment by wanderer** [comment]
awesome, finally i can remove that

**Comment by wanderer** [comment]
done in #12

**Comment by Kagami** [comment]
Thanks!
