### ISSUE TITLE
openssl 1.1.0 doesn't include libeay32.lib

### ISSUE THREAD

**Issue by bridiver** [cryptocoinjs/secp256k1-node#108]
secp256k1 fails to build with 1.1.0 because it doesn't have libeay32.lib, but linking against a local installation to build seems a bit odd. Wouldn't it make more sense to either include the libs or build them from source?

**Comment by fanatid** [comment]
I not sure, but isn't this issue related with https://github.com/bitcoin-core/secp256k1 ?

**Comment by bridiver** [comment]
@fanatid the problem is here https://github.com/cryptocoinjs/secp256k1-node/blob/master/binding.gyp#L10 and
https://github.com/cryptocoinjs/secp256k1-node/blob/master/binding.gyp#L121

**Comment by bridiver** [comment]
so even if we included our own build of openssl, we would still be stuck with the older version that has libeay32.lib

**Comment by bridiver** [comment]
there may also be an issue with https://github.com/bitcoin-core/secp256k1 if whatever was included in libeay32.lib no longer exists, but that seems doubtful with a minor version update

**Comment by fanatid** [comment]
I found that we don't need OpenSSL at all! Resolved in https://github.com/cryptocoinjs/secp256k1-node/commit/ab531d79bdb18b6f3fe03b612dca2d64b84093a4
