### ISSUE TITLE
Document/pad input message to 32 bytes

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#11]
I've noticed that `secp256k1` requires signed/verified message to be _exactly_ 32 bytes in length: https://github.com/bitcoin/secp256k1/blob/master/include/secp256k1.h#L110
If message is smaller verification of resulting signature is failed with other K-256 implementations.

So maybe `secp256k1-node` should document it somewhere near [here](https://github.com/wanderer/secp256k1-node/blob/master/index.js#L79), fail with error or pad input message with zeroes.

**Comment by wanderer** [comment]
ok I added padding in the padding branch. But I haven't tested against the other K-256 implementations yet.

**Comment by wanderer** [comment]
@Kagami would you happen to still have the script where you tested that?

**Comment by Kagami** [comment]
This one should work: https://github.com/indutny/elliptic/issues/24

**Comment by wanderer** [comment]
ok got it too work. Updated Docs and Bumped the version.

**Comment by Kagami** [comment]
Thanks. Just several nitpicks:
- It's better to not allocate buffer if msg length is already 32 bytes
- There is no check for messages longer than 32 bytes (`buf` indexes would be negative)

Maybe something like this is better:

``` js
function pad32(msg) {
  var zeroes;
  if (msg.length < 32) {
    zeroes = new Buffer(32 - msg.length);
    zeroes.fill(0);
    msg = Buffer.concat([zeroes, msg]);
  }
  return msg;
}
```

Or using only one allocation:

``` js
function pad32(msg) {
  var buf;
  if (msg.length < 32) {
    buf = new Buffer(32);
    buf.fill(0);
    msg.copy(buf, 32 - msg.length);
    return buf;
  } else {
    return msg;
  }
}
```

**Comment by wanderer** [comment]
Yep that would be much bettter.  Can you send me A PR if you have a sec?

**Comment by Kagami** [comment]
Done. #15
