### ISSUE TITLE
privateKeyExport

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/secp256k1-node#110]
It says DER format,  but is that to say it is twos complement?
Is it just a 32-byte buffer? 

> .privateKeyVerify(Buffer privateKey)
> Verify an ECDSA privateKey.

Is that *also* DER format? Why the sudden ECDSA prefix

(thanks in advance @fanatid)

**Comment by fanatid** [comment]
Only 32-byte buffer.

**Comment by dcousens** [comment]
https://github.com/cryptocoinjs/secp256k1-node/blob/2a8e5fde67fb8a076a9f1781621ed88d14d8938a/lib/index.js#L27

It exports the public key too?

**Comment by dcousens** [comment]
I feel like there is two types of `privateKey` here,  a DER `EC_PRIVKEY_EXPORT_DER_*`,  and then a 32-byte buffer that can be passed around.

**Comment by dcousens** [comment]
Right,  so  the `privateKeyExport` and `privateKeyImport` functions operate on DER,  everything else is a 32-byte buffer "private key".

Maybe those names are bad.

**Comment by fanatid** [comment]
probably I should give this method another name...
in bindings `ec_privkey_export_der` (from bitcoin-core/secp256k1) is used

**Comment by dcousens** [comment]
`privateKeyDERExport` and `privateKeyDERImport(derPrivateKey`? :man_shrugging:

**Comment by dcousens** [comment]
This still confuses me [and others] when referring to the documentation.
