### ISSUE TITLE
benchmark vs node native crypto

### ISSUE THREAD

**Issue by mvayngrib** [cryptocoinjs/secp256k1-node#112]
or do you know the approximate numbers?

**Comment by fanatid** [comment]
@mvayngrib you can run [benchmark](https://github.com/cryptocoinjs/secp256k1-node/blob/master/benchmarks/index.js) on your local machine :)
native is much faster, you can find approximately numbers in old revisions https://github.com/cryptocoinjs/secp256k1-node/tree/v3.0.0#performance
but [elliptic](https://github.com/indutny/elliptic) was improved, so better will run benchmark locally

**Comment by mvayngrib** [comment]
@fanatid i meant a benchmark against node's crypto module, not pure javascript libraries

**Comment by fanatid** [comment]
but node crypto module don't support secp256k1...

**Comment by mvayngrib** [comment]
@fanatid ah, that's my bad!
