### ISSUE TITLE
pointIsInfinity

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/secp256k1-node#118]
Any reason not to expose `secp256k1_ge_is_infinity`?

**Comment by fanatid** [comment]
Because [secp256k1](https://github.com/bitcoin-core/secp256k1) do not declare it in header file?

**Comment by dcousens** [comment]
You need to determine if the point is infinity or not for BIP32... [it appears they do the check in `secp256k1_eckey_pubkey_tweak_add`](https://github.com/bitcoin-core/secp256k1/blob/0b7024185045a49a1a6a4c5615bf31c94f63d9c4/src/eckey_impl.h#L70),  then `return 0` if it is infinity.

Great!  Except we then throw an exception for `return 0`.
I think the API might need to allow returning `null`...

**Comment by fanatid** [comment]
> I think the API might need to allow returning `null`...

Maybe, but if you return `null` you can not determinate what error it was. Is it was public key parse error or resulting public key is invalid?

**Comment by dcousens** [comment]
@fanatid if you previously parsed the pubkey,  you could easily know that the failure is because of something else... but indeed, you are right.

**Comment by dcousens** [comment]
@sipa any thoughts on what the best approach is here?

In our case,  we are looking at the BIP32 case:

> In case Ki is the point at infinity, proceed with the next value for i

There is no way to explicitly (and only) check if a point is infinity using the public API,  and [with `0` returned ambiguously](https://github.com/bitcoin-core/secp256k1/blob/84973d393ac240a90b2e1a6538c5368202bc2224/src/secp256k1.c#L490) it could be either?

**Comment by sipa** [comment]
@dcousens No, there is no need for exposing this function.

First of all, points at infinity cannot be serialized, so there is no way to even expose it.

Second, the tweak_add function you'd use to implement already does a check to see if the result is infinity, and fails if so.

**Comment by sipa** [comment]
@dcousens If you're using the API correctly (passing in valid public key), you'll only ever get 0 due to infinity or scalar overflow (both result in skipping to the next BIP32 index).

**Comment by dcousens** [comment]
Thanks @sipa 

@fanatid its on us then to not throw for a bad tweak, I think return `null` is the best course of action?

**Comment by dcousens** [comment]
@fanatid note how I am wrapping the API in https://github.com/bitcoinjs/bip32/commit/6412ab606b430704cd1da58129f1e12d6e17f35b,  to see why I think `null` return is appropriate.

Note that I use `secp256k1.publicKeyVerify` to verify any public keys are valid before then interacting with the other functions.

**Comment by fanatid** [comment]
@dcousens if we decide return `null` instead throwing error this will major version bump...

It's a good that you use `secp256k1.publicKeyVerify`, but I'm sure that not all `secp256k1-node` users do this.

What's wrong with `try/catch`?

**Comment by dcousens** [comment]
@fanatid the point is that it isn't an "error" condition at all similar to a parsing error,  it is a 
 legitimate possibility (albeit unlikely) despite valid user input.

**Comment by fanatid** [comment]
>  it is a legitimate possibility (albeit unlikely) despite valid user input.

I agree here... probably null will better, but we have what we have. I do not want major bump because 1 function. Or you have ideas how we can solve it?

**Comment by dcousens** [comment]
@fanatid major bump is major bump... we could suffix "Unsafe" or some-such if you want?

**Comment by fanatid** [comment]
Implemented in https://github.com/bitcoinjs/tiny-secp256k1 ?
