### ISSUE TITLE
Confusing output from npm install

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/secp256k1-node#120]
> secp256k1@3.3.0 install /home/.../node_modules/secp256k1
> prebuild-install || node-gyp rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

At a glance,  what I read is "Secp256k1 bindings compilation fail. Pure JS implementation will be used".

We should probably not have that in the command that is run,  as it reads as though it actually failed.

**Comment by fanatid** [comment]
Maybe use other words? We should run some command in any case, because otherwise if `secp256k1` will be in dependencies list all installation may fail.

**Comment by dcousens** [comment]
@fanatid low priority issue,  simply something that was confusing
