### ISSUE TITLE
Suggestion for avoiding all those openssl errors on Windows

### ISSUE THREAD

**Issue by Mayhem93** [cryptocoinjs/secp256k1-node#121]
*original issue at https://github.com/justmoon/node-bignum/issues/101*

I've come quite a long way here. Everything started with the **gencrypto** package which failed to install on my windows 10 machine because **eccrypto** was failing. Eccrypto was failing because in its **bindings.gyp** file the openssl lib path was static (and ofc I didn't have anything there).

But a few weeks ago I learned about https://github.com/Microsoft/vcpkg a nice tool to install libraries easily and with no hassle. Msbuild knows where all these libraries are installed and thus the linker doesn't need to know extra lib paths.

So I "fixed" **eccrypto**, tried rebuilding it and failed again because the **secp256k1** module was failing with a weird error :
```
'.' is not recognized as an internal or external command,
operable program or batch file.
```

Tried cloning that repo and build it myself, then I stumbled on yet another issue: **bignum** was failing to build because of that damned openssl lib. Then I just said to myself "ok, this apparent problem is more spread than I thought".

So I decided to ask you (and others) what do you think about this solution? From a user's stand point, there's just a couple more extra steps to do: integrate install vcpkg, `vcpkg install openssl` .

**Comment by fanatid** [comment]
Should not be used with v4.0.0
https://github.com/cryptocoinjs/secp256k1-node/pull/160
