### ISSUE TITLE
Prebuilt binaries for node:9 are not available

### ISSUE THREAD

**Issue by vith** [cryptocoinjs/secp256k1-node#122]
> prebuild-install WARN install No prebuilt binaries found (target=9.1.0 runtime=node arch=x64 platform=linux)

https://github.com/cryptocoinjs/secp256k1-node/blob/2b1ed90a922c82f204f55644929e4d2e2135aaf9/appveyor.yml#L5-L10

**Comment by fanatid** [comment]
Prebuilds for linux/macosx uploaded. Windows failed: https://ci.appveyor.com/project/fanatid/secp256k1-node/build/52/job/983whoxs37ojxcjg
Are you able build library on Windows with node 9?

**Comment by vith** [comment]
I don't normally do development on windows, but I installed `node-v9.1.0-x64.msi` and used `npm install --global --production windows-build-tools` and `npm i secp256k1` seems to have been successful (with a lot of warnings).

https://gist.github.com/vith/5aa4c9e1a08db488cd52bcd7ea740fcc

**Comment by fanatid** [comment]
Can you do same for 9.0.0?

**Comment by vith** [comment]
https://gist.github.com/vith/40d3e1d3d37f097b49d4a914045f0716 worked too

**Comment by fanatid** [comment]
Thanks, I started build for 9.1 on appveyor, will see soon. https://ci.appveyor.com/project/fanatid/secp256k1-node

**Comment by vith** [comment]
I was able to reproduce the failure like this:

```console
PS C:\Users\vith\Desktop\New folder> npm install npm@latest
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\vith\Desktop\New folder\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\vith\Desktop\New folder\package.json'
npm WARN New folder No description
npm WARN New folder No repository field.
npm WARN New folder No README data
npm WARN New folder No license field.

+ npm@5.5.1
added 460 packages in 6.08s
PS C:\Users\vith\Desktop\New folder> .\node_modules\.bin\npm install secp256k1
npm WARN npm npm does not support Node.js v9.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
C:\Program Files\nodejs\node.exe: src\node_zlib.cc:430: Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
```

See also https://github.com/npm/npm/issues/19019#issuecomment-340940842

Seems you need to avoid doing `npm -g install npm@latest` on node 9 for now.

**Comment by fanatid** [comment]
@vith thank you! pushed with yarn :))
windows prebuilds uploaded

**Comment by jmunson** [comment]
Seems like this was undone with https://github.com/cryptocoinjs/secp256k1-node/commit/9724304893df75301b906371da425c0afa1025e1

Was that intentional?

**Comment by fanatid** [comment]
Unfortunately or not, yes, this was intentional.
Do you have issues with building bindings locally?

**Comment by vith** [comment]
It's just an annoyance that it has to be rebuilt all the time because npm/yarn don't cache the result of node-gyp building it. In CI we preserve only the npm cache folder between jobs and not the unpacked node_modules.

With yarn it's even worse because even when it's already in node_modules and already built, yarn will rebuild it at every operation, even if you're just adding a completely unrelated package as a new dependency.

https://github.com/npm/npm/issues/3388

https://github.com/yarnpkg/yarn/issues/932

I don't *really* want to use precompiled binaries, but it was convenient given the state of javascript package managers.

There's also just a lot of compiler warning spam that makes CI logs even longer, so not seeing that was another nice side effect.

**Comment by ianaya89** [comment]
Hey, seems that I am facing a related issue using **appveyor**. The build gets stuck trying to install this library. 

I tried with yarn and npm (latest versions) and with Node 8 and 9. I am also using electron-builder. 

Any ideas of what could be wrong?

- `appveyor.yml`
```yml
image: Visual Studio 2017

platform:
  - x64

# cache:
#   - node_modules
#   - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn release

test: off
```

-  Build output

```
Build started
git config --global core.autocrlf input
git clone -q --branch=appveyor-issue git@github.com:MetronomeToken/metronome-desktop-wallet.git C:\projects\metronome-desktop-wallet
git checkout -qf c0a029795ab91c46b5226ba31f940cd6e98ccc07
Running Install scripts
Install-Product node 8 x64
Uninstalling node 4.8.7 (x86)...
Installing node 8.11.1 (x64)...
yarn
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "win32" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-linux@1.7.2: The platform "win32" is incompatible with this module.
info "app-builder-bin-linux@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.7.2: The platform "win32" is incompatible with this module.
info "app-builder-bin-mac@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-bloq@1.1.0" has incorrect peer dependency "eslint-config-standard@>= 11".
warning " > eslint-config-bloq@1.1.0" has unmet peer dependency "eslint-plugin-jsdoc@>= 3".
warning " > eslint-config-bloq@1.1.0" has incorrect peer dependency "eslint-plugin-node@>= 6".
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder version=20.5.1
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • rebuilding native production dependencies platform=win32 arch=x64
  • rebuilding native dependency name=keccak
  • rebuilding native dependency name=websocket
  • rebuilding native dependency name=sha3
  • rebuilding native dependency name=secp256k1
```
