### ISSUE TITLE
Add support for calculating inverse of a private key

### ISSUE THREAD

**Issue by kripod** [cryptocoinjs/secp256k1-node#124]
This can be useful for decrypting points multiplied by a key.

**Comment by kripod** [comment]
Currently, I'm using the following (JS-only) workaround to achieve my goal:

```js
import BigInt from 'secp256k1/lib/js/bn';

const inverseOfPrivateKey = privateKey =>
  BigInt.fromBuffer(privateKey)
    .uinvm()
    .toBuffer();
```

There is native support for this operation by the `secp256k1_scalar_inverse` method of the secp256k1 library.

**Comment by fanatid** [comment]
@kripod better use `elliptic`/`bn.js`, at least Fedor's libraries was reviewed by more people

I think we will not put this to public API until [secp256k1](https://github.com/bitcoin-core/secp256k1) will not provide it.

**Comment by kripod** [comment]
@fanatid secp256k1 provides native support for this, as I have already mentioned in my previous (edited) comment.

**Comment by fanatid** [comment]
`secp256k1_scalar_inverse` is not defined in `.h` file: https://github.com/bitcoin-core/secp256k1/blob/c95f6f1360a87bba61622cbaa0eb714c241a5d90/include/secp256k1.h

I do not want create another workaround as for ECDH.

**Comment by kripod** [comment]
I just created https://github.com/bitcoin-core/secp256k1/issues/500 for this purpose.

**Comment by dcousens** [comment]
Do you mean `secp256k1_ec_privkey_negate`?

**Comment by kripod** [comment]
@dcousens Yes, exactly!

**Comment by kripod** [comment]
I'll start working on a pull request. I've never been working with Node.js bindings before, but I will try my best to implement the `secp256k1_ec_privkey_negate` function.

**Comment by kripod** [comment]
I'm not sure why the Travis CI build didn't pass, as 4 of the build jobs didn't even start!

**Comment by kripod** [comment]
@dcousens It turns out that `secp256k1_ec_privkey_negate` is **not** the same as the inverse.

**Comment by dcousens** [comment]
@kripod can you explain the difference in this context?

**Comment by kripod** [comment]
@dcousens `secp256k1_ec_privkey_negate` calculates `n - privKey` (where `n` is the order of the curve's base point), but I would like to get `inverse privKey modulo n`. I just fixed the negation function in my PR, and started working on implementing the latter functionality.

**Comment by kripod** [comment]
I’ve just finished working on the pull request and also clarified the difference between `privateKeyNegate` and `privateKeyModInverse` in the API docs.

**Comment by dcousens** [comment]
Thanks @kripod
