### ISSUE TITLE
Should the prefix 1 byte sting of public key be documented?

### ISSUE THREAD

**Issue by Changdao** [cryptocoinjs/secp256k1-node#127]
rt.

**Comment by fanatid** [comment]
I do not think so. If we going to do this, we should document rest of prefixes, encodings and math.
Anyone can check public key prefix in source code.
33 bytes: 0x02 - y is even number, 0x03 - y is odd
65 bytes: 0x04, but also old prefixes: 0x06 - y is even, 0x07 is odd
