### ISSUE TITLE
Doesn't NPM install on Linux, Node 10

### ISSUE THREAD

**Issue by youurayy** [cryptocoinjs/secp256k1-node#130]
![image](https://user-images.githubusercontent.com/588573/42139489-85ffbaa2-7d97-11e8-98bc-4da257e1af08.png)

(does the same without `@latest`)
(env is Docker on Hyper-V/Windows 10)

**Comment by youurayy** [comment]
furthermore, cloning the repo (+init submodules) and doing `npm install` fails at:

![image](https://user-images.githubusercontent.com/588573/42139588-94138004-7d99-11e8-85fa-c586fcb4aaf9.png)

**Comment by youurayy** [comment]
yarn seems to work, I've updated the title
(still fails on bignum when building inside the source repo)

**Comment by fanatid** [comment]
Please try 4.0.0
https://github.com/cryptocoinjs/secp256k1-node/pull/160
