### ISSUE TITLE
wont build on nix systems without bash

### ISSUE THREAD

**Issue by AVVS** [cryptocoinjs/secp256k1-node#133]
ie, in alpine linux only shell is present and 

https://github.com/cryptocoinjs/secp256k1-node/blob/master/utils/has_lib.sh#L1

uses bash

**Comment by fanatid** [comment]
Tested and fixed in https://github.com/cryptocoinjs/secp256k1-node/commit/005da3395f7a37dc02d86d61af9e79dc905fab67
Published as 3.5.2
