### ISSUE TITLE
How to create a second generator point (H)

### ISSUE THREAD

**Issue by gavinmcdermott** [cryptocoinjs/secp256k1-node#134]
I am in the process of implementing pedersen commitment functionality in a project, and I am wondering the best way is to create a second generator point (`H`). 

In the Grin code, they have defined it as the hash of the base generator `SHA256(G)`. Links to relevant dialogue and code are [here](https://www.grin-forum.org/t/definition-of-h-and-g/209/4).

I am new to this lib, and learning the ropes when it comes to implementing the guts of crypto-systems in JS. Can you provide direction for the best way to generate `H`?

Thanks in advance.

**Comment by fanatid** [comment]
@gavinmcdermott this is only bindings, better submit issue to [bitcoin-core/secp256k1](https://github.com/bitcoin-core/secp256k1) or wait answer in https://github.com/indutny/elliptic/issues/166

**Comment by gavinmcdermott** [comment]
Thanks; will see what shows up there.
