### ISSUE TITLE
for browser? is js

### ISSUE THREAD

**Issue by youfeed** [cryptocoinjs/secp256k1-node#136]
Hello, can this ECC library be compiled into browser?

Forgive me for not packing.

**Comment by fanatid** [comment]
[elliptic](https://github.com/indutny/elliptic) is used as fallback for browsers

**Comment by youfeed** [comment]
Thank you. I'll learn how to use it in any browser.
1. generate private key public key pair [registration]
2. signing the hash of the transaction information with the private key and signing the transaction with the private key.
3. load the private key and calculate the public key [matching transaction] with the private key.
4. signature + public key + transaction information
I have a question, if I sign correctly, I can read out the public key in the signature, is it, using the public key to verify the signature information?

**Comment by fanatid** [comment]
This repo about issues for package [secp256k1](https://www.npmjs.com/package/secp256k1), not about crypto questions.
