### ISSUE TITLE
v3.6.0 breaks ethereumjs-devp2p

### ISSUE THREAD

**Issue by vpulim** [cryptocoinjs/secp256k1-node#138]
Peers are no longer able to successfully handshake.

`ecdhUnsafe()` seems to be returning different values between `3.5.2` and `3.6.0`

**Comment by fanatid** [comment]
wow, do you have data for reproducing this issue?

**Comment by vpulim** [comment]
Sure, here's some test code that I ran on ``3.5.2`` and ``3.6.0`` and got different results:
```
const secp256k1 = require('./index')
const publicKey = Buffer.from('03d0d06028880fac08fc7d481a87fca5845be7921ca83b49ed4697ca5c62b701c9', 'hex')
const privateKey = Buffer.from('9658d24d521e8f2d460722de887792441907079b4e76cdc341c3732600900477', 'hex')
console.log(secp256k1.ecdhUnsafe(publicKey, privateKey, true).toString('hex'))
```

`3.5.2`:
```
>> 033a353c2b6934e8746c363219eb718477a87cf5565eaa920db67258990b444d94
```

`3.6.0`:
```
>> 03944d440b995872b60d92aa5e56f57ca8778471eb1932366c74e834692b3c353a
```

NOTE: The keys were generated using `test/util.js`:
```
const privateKey = util.getPrivateKey()
const publicKey = util.getPublicKey(privateKey).compressed
```

Also, I ran the test using node LTS versions `6.16.0`, `8.15.0` and `10.15.0` and all generated the same results.
