### ISSUE TITLE
EC is not a constructor

### ISSUE THREAD

**Issue by fainashalts** [cryptocoinjs/secp256k1-node#141]
Hi there! If this question does not have enough information please let me know and I'll do my best to supplement. I am using this module in my node project, and am getting an error "EC is not a constructor" -- looking at the code, I see that on line 10 there is an attempt to use EC as a constructor, and attempting to console log inside of the elliptic module does not work, so it seems like something is going on re: the connection between this module and elliptic.

I'm bringing this up here because I wonder if this is bug in secp256k1-node? Thanks, please let me know what you think!

**Comment by fanatid** [comment]
Can you paste code which cause error?

**Comment by fainashalts** [comment]
This actually wound up being due to a different issue/module. Sorry about that, and thanks!

**Comment by rparkchan** [comment]
> This actually wound up being due to a different issue/module. Sorry about that, and thanks!

Any insight on what this was caused by? Seeing similar issues in a project
