### ISSUE TITLE
Fails to install on Node 12

### ISSUE THREAD

**Issue by satazor** [cryptocoinjs/secp256k1-node#142]
Node 12 has just released but this library is failing to compile, maybe due to v8 changes.

You may see a travis log here: https://travis-ci.org/ipfs-shipyard/js-idm-wallet/jobs/524722975#L587

**Comment by fanatid** [comment]
Related issue https://github.com/bitcoinjs/tiny-secp256k1/issues/38

**Comment by fanatid** [comment]
Should be solved with version 3.7.0
