### ISSUE TITLE
does openssl 1.1.1b in recent node versions support secp256k1 well enough?

### ISSUE THREAD

**Issue by sam-github** [cryptocoinjs/secp256k1-node#145]
Hi, I just found this package from the bignum issue.

Is it possible that recently node.js has sufficient support for this curve to make this addon unnecessary?

If OpenSSL (12 and 11 use 1.1.1b, and node 10 is at 1.1.1a but will be 1.1.1b soon) doesn't support what you need, node can't. But if OpenSSL has support and it isn't exposed in a usable form, it would be helpful to open a feature request on nodejs/node describing what is missing.

Note: I don't use bitcoin directly, but I do have an interest in allowing the crypto ecosystem to depend less on binary addons by ensuring node's crypto library exposes necessary functionality.

**Comment by fanatid** [comment]
Hi @sam-github it's good suggestion, and of course if such features will be in node crypto this will great experiment, not only for bitcoin/cryptocurrencies JS community.
But this addon uses optimized and well verified library https://github.com/bitcoin-core/secp256k1 which used in bitcoin core directly, so this package still have purpose for existing.

**Comment by sam-github** [comment]
Sure, in no way did I intend a slight on this library. It's just that addons tend to be quite painful for some user groups. It sounds like yarn is trying to get rid of install scripts, which will make them even worse as I suspect that will break node-pre-gyp, and I've been looking at some dev efforts to add security policy support to node, and they could also ban addons. Anyhow, my main point with this was just to make sure you understand that if you (or someone) do ever try to go pure-js and use the node crypto API, there are at least a few of us working on node core that would help out if you run into issues with missing features.
