### ISSUE TITLE
Passing output buffer in

### ISSUE THREAD

**Issue by emilbayes** [cryptocoinjs/secp256k1-node#152]
Hi!

In sodium-native we use this pattern where the developer can pass in the Buffer that data should be written into. This is especially handy if you want to leverage special "Buffers", like the "Secure Buffers" we have, where the memory pages used have had certain flags set, such as no swap, canaries, not being included in core dumps and such.

Is this something we could do here as well? I'm imagining a optional, last parameter on relevant functions

**Comment by fanatid** [comment]
Hi @emilbayes .

Are you mean `sodium_malloc` from `sodium-native`? https://github.com/sodium-friends/sodium-native/blob/eea00874bb92ae92f818bd920da05c5dca126677/binding.cc#L48

I think it's possible as optional argument, yes. But from other side resulted data stored not only in output buffer, but also in elliptic/bn.js as points, so probably such secure buffers does not make a sense?

**Comment by emilbayes** [comment]
@fanatid does secp256k1 malloc internally? Because that could cause sensitive intermediates to be leaked. But otherwise yes, the output of that function is wrapped in Buffer and we call them secure buffers because the backing memory is more than just normal memory pages.

**Comment by fanatid** [comment]
Yes, both JS and bindings allocate memory internally where result stored (which will be moved to resulted buffers).
https://github.com/cryptocoinjs/secp256k1-node/blob/2f1c956d71c39e5667e6285a6dafc15ce28e86f0/lib/elliptic/index.js#L209
https://github.com/cryptocoinjs/secp256k1-node/blob/2f1c956d71c39e5667e6285a6dafc15ce28e86f0/src/ecdsa.cc#L82

**Comment by emilbayes** [comment]
Sorry, I didn't mean in this code but in core secp256k1. I see that have "No heap allocations" as a feature so it would be a great fit. The 2nd example is just a stack allocation which I'm personally not too interested in (some people care about smashing the stack)

**Comment by fanatid** [comment]
Sorry, I was wrong. You are correct, bindings with [bitcoin-core/secp256k1](https://github.com/bitcoin-core/secp256k1) makes only stack allocations here I think.

**Comment by fanatid** [comment]
@emilbayes please check [fanatid/fcrypto](https://github.com/fanatid/fcrypto), now it's possible pass custom Uint8Array in for output

**Comment by fanatid** [comment]
Now it's possible with version 4.0.0, custom Uint8Array can be passed as last argument.
https://github.com/cryptocoinjs/secp256k1-node/pull/160
