### ISSUE TITLE
Explain build warnings

### ISSUE THREAD

**Issue by fulldecent** [cryptocoinjs/secp256k1-node#155]
People using secp256k1 in their projects are used to seeing many build errors.

It will be helpful if a note here in the README explains why these build errors can be safely ignored.

**Comment by fulldecent** [comment]
-OR- what resources you need to help handle those warnings.

**Comment by fanatid** [comment]
PR's are welcome. I planning update project to [n-api](https://nodejs.org/api/n-api.html) and add prebuilds, but no ETA right now. Most probably in January 2020.

**Comment by fanatid** [comment]
n-api version in [fanatid/fcrypto](https://github.com/fanatid/fcrypto)

**Comment by fanatid** [comment]
New version 4.0.0 with n-api prebuilds released. Targets split with better flags, so even compilation will be required, there should not be warnings.
https://github.com/cryptocoinjs/secp256k1-node/pull/160
