### ISSUE TITLE
How to export public key in DER format?

### ISSUE THREAD

**Issue by Lazar955** [cryptocoinjs/secp256k1-node#157]
Hey i am having trouble exporting public key in DER format, there is no privateKeyExport implemented? Or am i missing something?

**Comment by fanatid** [comment]
Public key or private key? `privateKeyExport` (private key to DER) is implemented https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md#privatekeyexportbuffer-privatekey--boolean-compressed--true---buffer

**Comment by Lazar955** [comment]
@fanatid My bad, i meant to say there is privateKeyExport but there is no publicKeyExport. How would i go about exporting public key? Thanks

**Comment by fanatid** [comment]
[bitcoin-core/secp256k1](https://github.com/bitcoin-core/secp256k1) do not have functions for exporting public keys in DER, only [signature](https://github.com/bitcoin-core/secp256k1/blob/master/contrib/lax_der_parsing.h) and [private key](https://github.com/bitcoin-core/secp256k1/blob/master/contrib/lax_der_privatekey_parsing.h). So if you need this, you will need implement it by yourself :(
