### ISSUE TITLE
Update elliptic package to fix vulnerability

### ISSUE THREAD

**Issue by rabomarnix** [cryptocoinjs/secp256k1-node#158]
A medium severity vulernability was reported some time ago. It regards a Timing Attack in the `elliptic` package. This vulnerability is fixed in version 6.5.2.

Details: https://app.snyk.io/vuln/SNYK-JS-ELLIPTIC-511941

I will open a PR soon

**Comment by fanatid** [comment]
Thanks. Updated in https://github.com/cryptocoinjs/secp256k1-node/commit/c44ff4515d734167b6ab963c20924639da5ab816, published as 3.8.0
