### ISSUE TITLE
Documentation: msg should be msghash

### ISSUE THREAD

**Issue by bitsanity** [cryptocoinjs/secp256k1-node#163]
It looks like the ecdsaSign() function expects the hash of a message instead of the message itself. 
The Usage section could be clearer:

```js
// msghash should be 32-byte hash of a message, e.g. sha256(msg)
// here using random data just for illustration and test
const msghash32 = randomBytes(32)

[snip]

// sign the message
const sigObj = secp256k1.ecdsaSign(msghash32, privKey)

```

This would also fix #132

**Comment by fanatid** [comment]
Yep, would be good. Do you want submit PR?

**Comment by bitsanity** [comment]
Attached patch file (had to append .txt because github doesn't recognize that file type): 

[fix_issue_163.patch.txt](https://github.com/cryptocoinjs/secp256k1-node/files/4155198/fix_issue_163.patch.txt)

**Comment by fanatid** [comment]
Added in https://github.com/cryptocoinjs/secp256k1-node/commit/d9f7bf09a4c6f9ffd91615adf9c6d2b301107fa4
