### ISSUE TITLE
Missing Documentation 

### ISSUE THREAD

**Issue by geekrishabh** [cryptocoinjs/secp256k1-node#165]
How to upgrade from 3.x to 4.x .

I am using [Eth-Crypto](https://github.com/pubkey/eth-crypto) But it's not working on React Native.

**Comment by fanatid** [comment]
> How to upgrade from 3.x to 4.x .

Compare two versions of API and make required changes.
https://github.com/cryptocoinjs/secp256k1-node/blob/v3.x/API.md
https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md
