### ISSUE TITLE
Generation of JWK from key outputs

### ISSUE THREAD

**Issue by csuwildcat** [cryptocoinjs/secp256k1-node#176]
I am trying to generate a standard JWK representation (https://tools.ietf.org/html/rfc7518#section-6.2.1.3) from the outputs of the key generation methods, but was not clear how to generate the `y` points for the public key, and the `d` point for the private key. I see the example code to get the `x` point, but am unsure what the `y` points equates to and whether the output of the private key is equivalent to the JWK private key representation's `d` point .Excuse my ignorance if this is an obvious question.

**Comment by junderw** [comment]
crv parameter of JWT doesn't support SECP256k1 iirc.

But to get d (private key) and x and y is the following. All values are big endian, and according to JWT should just be base64 encoded.

```js
const { randomBytes } = require('crypto')
const secp256k1 = require('secp256k1')

function generateD() {
  let privKey
  do {
    privKey = randomBytes(32)
  } while (!secp256k1.privateKeyVerify(privKey))

  // 32 byte Buffer object
  return privKey
}

function generateXY(d) {
  const pubKey = secp256k1.publicKeyCreate(d, false) // false means uncompressed, so Y value is contained and not shortened

  // x and y are both 32 byte Buffers
  return {
    x: pubKey.slice(1, 33),
    y: pubKey.slice(33, 65)
  }
}
```

**Comment by csuwildcat** [comment]
Thank you for the detailed help! We at Microsoft pushed to have secp256k1 added as a standard JW* crv/alg and it is now registered as secp256k1/ES256K. Here's the IETF RFC, for reference: https://tools.ietf.org/html/rfc8812#section-3.2
