### ISSUE TITLE
Is there a method to encrypt data with a specific public key ?

### ISSUE THREAD

**Issue by JW-Rami** [cryptocoinjs/secp256k1-node#196]
I can't find documentation about the encryption part for encrypt data with a specific public key

**Comment by junderw** [comment]
ECDSA is not for encryption.

There is a separate standard called ECIES which allows you to encrypt and decrypt data using symmetric keys generated from ECDH keys.

https://www.npmjs.com/package/eccrypto

This library supports ECIES, and the public and private keys generated by this library are compatible with that library.
