### ISSUE TITLE
privateKeyModInverse not exported anymore

### ISSUE THREAD

**Issue by vostrnad** [cryptocoinjs/secp256k1-node#198]
It seems the function `privateKeyModInverse` was removed in #160 without explanation (as far as I can tell). Was that intentional? Can we have it back?

**Comment by fanatid** [comment]
ouch, it's bad that we removed it without a note about this in the pull request
`bitcoin-core/secp256k1` do not export this function, I'm not sure that we need to implement it by ourselves :confused:  https://github.com/bitcoin-core/secp256k1/blob/d644dda5c9dbdecee52d1aa259235510fdc2d4ee/include/secp256k1.h

**Comment by vostrnad** [comment]
Thank you for the response, I guess you can just amend the release note for [v4.0.0](https://github.com/cryptocoinjs/secp256k1-node/releases/tag/v4.0.0).
