### ISSUE TITLE
add ECDH functions

### ISSUE THREAD

**Issue by wanderer** [cryptocoinjs/secp256k1-node#28]

**Comment by Kagami** [comment]
:+1: would be very nice to have. Right now I have to use custom OpenSSL wrapper for that: https://github.com/bitchan/eccrypto/blob/master/ecdh.cc

**Comment by fanatid** [comment]
@Kagami I add ECDH in v2.0.0, but [secp256k1](https://github.com/bitcoin/secp256k1/) implementation differs from yours, because apply sha256 to result..

**Comment by Kagami** [comment]
Indeed.. It's a bit unfortunate, I guess I'm locked to OpenSSL for a while.
I'm wondering why would they do that, elliptic doesn't hash derived secret for example. Probably some additional security measure.

**Comment by wanderer** [comment]
@Kagami I'm guessing since it multiplying two points together, a publicKey and privateKey, that the result isn't necessarily going to result in an uniform distribution.

**Comment by fanatid** [comment]
@Kagami instead openssl you can try write your own implementation secp256k1_ecdh that use internal functions of secp256k1 (secp256k1_ecmult_const/secp256k1_ge_set_gej/secp256k1_fe_normalize ...). Probably it will be faster.

**Comment by Kagami** [comment]
@fanatid thanks for the hint, I will look into it. They also have [PR](https://github.com/bitcoin/secp256k1/pull/262) for x-only ECDH which is perfectly fine for my needs.
