### ISSUE TITLE
Install failing on ubuntu 14.04

### ISSUE THREAD

**Issue by kjameslubin** [cryptocoinjs/secp256k1-node#29]
```
make: Entering directory `/home/kjameslubin/ethtemp/bloc/node_modules/secp256k1-node/build'
  CXX(target) Release/obj.target/secp256k1/functions.o
In file included from ../functions.cc:1:0:
../node_modules/nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:1178:27: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
                           v8::String::REPLACE_INVALID_UTF8;
                           ^
../functions.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sign(Nan::NAN_METHOD_ARGS_TYPE)’:
../functions.cc:66:59: error: no matching function for call to ‘v8::Array::Set(int, node::Buffer*)’
       results->Set(0, node::Buffer::New(output, outputlen));
etc..

```

I've tried to install several ways. The errors are all variants of the above.

UPDATE: I checked, and I am able to build sipa's secp256k1 separately from secp256k1-node. So more data there..

**Comment by wanderer** [comment]
@kjameslubin thanks for reporting this! 1) are you using version ~1.0.0 of secp256k1? 2) what version of node.js are you using?

**Comment by wanderer** [comment]
probably related https://github.com/joyent/node/commit/881ac26f27f4ac9585d66c8d8a67d5b246a23d1b

**Comment by kjameslubin** [comment]
```
~> node --version
v0.10.25
```

I cloned the most recent (master) secp256k1 after seeing that secp256k1-node depended on it. It doesn't have version tags.

**Comment by wanderer** [comment]
node version 0.10 is not supported any more. Try 0.11 or 0.12

**Comment by wanderer** [comment]
any luck with 11 or 12 @kjameslubin ?

**Comment by kjameslubin** [comment]
Installs on 12. You should maybe just include a clearer warning about this. Also if you are reinstalling from 10.x, then you have to reinstall everything

**Comment by Kagami** [comment]
@wanderer @fanatid why node 0.10 is no longer supported? Latest `nan` perfectly supports it and it's still in use in LTS distros like Ubuntu 14.04.

**Comment by fanatid** [comment]
I don't know why 0.10 wasn't supported. 0.10 not in [LTS](https://github.com/nodejs/LTS/) period anymore, now (and next 11 month) in maintenance mode. People can use [nvm](https://github.com/creationix/nvm) for installing new node version but probably we should add 0.10 if it isn't hard.

**Comment by Kagami** [comment]
Any plans to port to 0.10? Should I create an issue?
