### ISSUE TITLE
allow nonce data in API

### ISSUE THREAD

**Issue by wanderer** [cryptocoinjs/secp256k1-node#30]

**Comment by fanatid** [comment]
I think it doesn't make a sense, library should implement operations on data not generating.

**Comment by wanderer** [comment]
The Title was confusing. But for example users should be able to specify the nonce [here](https://github.com/bitcoin/secp256k1/blob/master/include/secp256k1.h#L463).

**Comment by fanatid** [comment]
Yep, we can do this if allow passing options to sign/signSync. Probably it should also allowed pass noncefp.

**Comment by fanatid** [comment]
Moved to #49
