### ISSUE TITLE
Can't use with node-gyp rebuild anymore

### ISSUE THREAD

**Issue by Frankenmint** [cryptocoinjs/secp256k1-node#31]
Seems to conflict with Node-gyp rebuild when trying to make Augur.js

**Comment by wanderer** [comment]
@Frankenmint what error are you getting?

**Comment by Frankenmint** [comment]
Failed at the secp256k1@1.1.3 install script 'node-gyp rebuild'.
This is most likely a problem with the secp256k1 package,
not with npm itself.
Tell the author that this fails on your system:
node-gyp rebuild

...  Specifically this is where if fails to build ...

 npm install

> fsevents@0.3.8 install .../augur/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

will be removed upon resolution >>[I've installed the lastest updates for node, gyp, npm, and also for Xcode (I think my clang compiler defaults to pulling from Xcode since this is Macbook)]  << will be removed upon resolution

**Comment by wanderer** [comment]
@Frankenmint kinda looks like a fsevents problem to me. Not seeing where secp256k1 is failing.

**Comment by wanderer** [comment]
@Frankenmint this lovell/sharp/issues/80 looks like the similar problem. Can you try running `xcode-select --install` ?

**Comment by Frankenmint** [comment]
I already have Xcode Command Line Tools installed - I'll try to update it and see if that solves though.

**Comment by wanderer** [comment]
@Frankenmint any luck?

**Comment by Frankenmint** [comment]
Yea I got it figured out.  Your package worked by itself.  There is a 3rd party dependency, couldn't tell if it was keystore or keythereum.  Basically there was a system update recently which removed a file that was once there.  My System couldn't find it and crashed the build.  I think that OSX now works with a plist instead of the file so creating an empty file and symbolic linking to it saved my day:

```
sudo echo > /usr/local/bin/ldconfig
sudo chmod +x /usr/local/bin/ldconfig
```
