### ISSUE TITLE
Can't install the module with node 4.1.1

### ISSUE THREAD

**Issue by asinyagin** [cryptocoinjs/secp256k1-node#32]
Hey,

Looks like secp256k1 can't be compiled with node 4.1.1. Here's the error: http://pastebin.com/3Z7z0aRV

**Comment by wanderer** [comment]
@asinyagin can you try the lastest version 1.1.4? `npm install secp256k1@1.1.4`

**Comment by asinyagin** [comment]
@wanderer yeah, 1.1.4 is compiled. sorry, i didn't notice ethereumjs-tx from npm requires secp256k1 v1.1.1.

**Comment by wanderer** [comment]
@asinyagin the lastest ethereumjs-tx uses the secp256k1 https://github.com/ethereum/ethereumjs-tx/blob/master/package.json#L19 .
