### ISSUE TITLE
1.1.4 produce different signatures compared to 0.0.15

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#33]
``` bash
$ npm i secp256k1
$ cat 1.js 
var createHash = require("crypto").createHash;
var secp256k1 = require("secp256k1");
var privateKey = Buffer(32);
privateKey.fill(1);
var msg = createHash("sha256").update("test").digest();
console.log(secp256k1.sign(privateKey, msg, true).toString("hex"));
$ node 1.js
304402206f97030cee64f6b9a04575720a0d42ce808c2122d76beefa15b96d9211dafb9e0220304f547f6eed9c8368deeff997918b349ca617be678f4726c04a1588ce15cf4b
$ npm i secp256k1@0.0.15
$ sed -i 's/, true//' 1.js
$ node 1.js               
3044022078c15897a34de6566a0d396fdef660698c59fef56d34ee36bef14ad89ee0f6f8022016e02e8b7285d93feafafbe745702f142973a77d5c2fa6293596357e17b3b47c
```

0.0.15 signatures are equal to elliptic's canonical DER signatures (see [here](https://github.com/bitchan/eccrypto/blob/e57608d1ad1b46bd23823a83603bfb1a7a7d0656/browser.js#L83)). Am I missing something?

**Comment by wanderer** [comment]
So the nonce function may have changed a bit. But it should be ok as long as elliptic can verify the signature.

**Comment by wanderer** [comment]
@Kagami we are testing DER sigs againts `ecdsa` here https://github.com/wanderer/secp256k1-node/blob/master/test/index.js#L24-L26  Maybe it wouldn't be a bad Idea to test against elliptic too

**Comment by Kagami** [comment]
I can't see the differences in default nonce function since https://github.com/bitcoin/secp256k1/commit/bbd5ba7cfa03db851ae1de6d7be0e4c072cb6a54 Maybe signature serialization was changed in `secp256k1-node`? I had similar [issue with elliptic](https://github.com/indutny/elliptic/issues/24), there was lack of option to make it canonical.

I think it's much easier to test for the exact value. I test different implementation too of course, but I feel much more confident if I get the exact same values for different version of libs and runtimes.

**Comment by wanderer** [comment]
well I just use this to serialize https://github.com/bitcoin/secp256k1/blob/master/include/secp256k1.h#L291-L307 

the C code limits the S-value; see this comment
https://github.com/bitcoin/secp256k1/blob/master/include/secp256k1.h#L345-L347
maybe this introduce the difference.

**Comment by fanatid** [comment]
I check with new version (PR: #39), looks that is all fine:

``` js
var createHash = require('crypto').createHash
var EC = require('elliptic').ec
var bindings = require('./bindings')

var ec = new EC('secp256k1')

var privateKey = Buffer(32).fill(1)
var msg = createHash('sha256').update('test').digest()

var eSig = new Buffer(ec.sign(msg, privateKey, {canonical: true}).toDER()).toString('hex')
var bSig = bindings.signatureExport(bindings.signSync(msg, privateKey).signature).toString('hex')

console.log(eSig === bSig) // true (3044022078c15897a34de6566a0d396fdef660698c59fef56d34ee36bef14ad89ee0f6f8022016e02e8b7285d93feafafbe745702f142973a77d5c2fa6293596357e17b3b47c)
```

**Comment by Kagami** [comment]
I built your branch and it's indeed returns exact the same signatures now. Thank you!
