### ISSUE TITLE
Decompressing public key

### ISSUE THREAD

**Issue by h0vhannes** [cryptocoinjs/secp256k1-node#34]
Hi,

`decompressPublickey` doesn't work at this moment. Actually, it is equal to `undefined`. This is due to the following commit in https://github.com/bitcoin/secp256k1
https://github.com/bitcoin/secp256k1/commit/23cfa914d2d17dfc3d28ae3b10d95385dac5d835#diff-0d77700fa6e05639431c962ffaa5365aL285
Here `secp256k1_ec_pubkey_decompress` was removed from the code, so decompressPublickey references nothing.

After all, I just want to decompress a compressed public key in node to encrypt a message with ECIES encryption having just a compressed key.

What should I do in this situation?

Thanks in advance, Hovhannes.

**Comment by h0vhannes** [comment]
This is the solution if someone is interested

```
var elliptic = require('elliptic');
var ec = new elliptic.ec('secp256k1');
var publicKeyUncompressed = ec.keyFromPublic(PublicKeyCompressed, 'hex').getPublic(false, 'hex');
```

**Comment by wanderer** [comment]
@h0vhannes thanks for the solution. I'm going to leave this open till I get a chance to write a better API for the keys.

**Comment by h0vhannes** [comment]
Thanks @wanderer, will wait for it !

**Comment by fanatid** [comment]
@h0vhannes with v2.x you can use [publicKeyConvert](https://github.com/wanderer/secp256k1-node/blob/master/API.md#publickeyconvertbuffer-publickey--boolean-compressed--true---buffer)

**Comment by h0vhannes** [comment]
thanks
