### ISSUE TITLE
Option to create uncompressed public key from private key

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#46]
It would be nice to have ability to create uncompressed public key without extra step (private -> compressed public -> uncompressed public).

**Comment by fanatid** [comment]
Yes it would be nice but I specially remove all options, because in other case you need more checks in code and this make code more complex. Also you need more tests for coverage all possible options.
I want to see functions in this library as low-level as possible, probably we even should remove throwing errors (except type checking because it raise core dumped).

**Comment by Kagami** [comment]
> but I specially remove all options

What about separate function `.publicKeyCreateUncompressed(Buffer secretKey)` then?

**Comment by wanderer** [comment]
imo the nicest API would be to return a `keyObject` that would have `serialize([compressed=bool])` as well as `publicKeyTweakAdd` and related methods. But that would be more round trip from JS to C++. which I think would be slower. Native binding should put efficiency first place.

**Comment by fanatid** [comment]
Probably `keyObject` don't take much overhead. I will try to write benchmark on this week.

**Comment by fanatid** [comment]
I write benchmark, with object it's slower on ~2%. Although object slower I'm would prefer call serialize instead pass options.
[KeyObject](https://github.com/wanderer/secp256k1-node/blob/issue-46-benchmark/src/addon.cc#L19)
[js benchmark](https://github.com/wanderer/secp256k1-node/blob/issue-46-benchmark/benchmark.js)

``` bash
$ node benchmark.js 
api v2.x x 13,941 ops/sec ±0.86% (101 runs sampled)
with object x 14,031 ops/sec ±0.76% (100 runs sampled)
Fastest is with object
$ node benchmark.js 
api v2.x x 14,227 ops/sec ±0.22% (101 runs sampled)
with object x 14,024 ops/sec ±0.70% (99 runs sampled)
Fastest is api v2.x
$ node benchmark.js 
api v2.x x 14,231 ops/sec ±0.29% (99 runs sampled)
with object x 13,695 ops/sec ±1.89% (98 runs sampled)
Fastest is api v2.x
$ node benchmark.js 
api v2.x x 14,208 ops/sec ±0.59% (101 runs sampled)
with object x 14,021 ops/sec ±0.82% (101 runs sampled)
Fastest is api v2.x
$ node benchmark.js 
api v2.x x 14,235 ops/sec ±0.53% (99 runs sampled)
with object x 13,953 ops/sec ±0.80% (101 runs sampled)
Fastest is api v2.x
```

**Comment by Kagami** [comment]
Is there any difference between option of `.serialize` or `.publicKeyCreate` functions? I don't mind either way though.
Note also that length of the compressed key is 33 bytes. Now you always create buffer with length of 65. I'm not sure how [that works](https://github.com/wanderer/secp256k1-node/blob/a8e1f7e0e7fdc58b31774bcf6b0a4b291d8e490d/src/publickey.cc#L54-L56) too.

**Comment by fanatid** [comment]
@Kagami the main benefit of `PublicKey` (also we should create object `Signature`) object is that you don't need call `secp256k1_ec_pubkey_parse/secp256k1_ec_pubkey_serialize` every time when you want verify/ecdh/tweaks or make other operations with public keys.

**Comment by fanatid** [comment]
Move to #49
