### ISSUE TITLE
RFC: non-hashed ecdh

### ISSUE THREAD

**Issue by axic** [cryptocoinjs/secp256k1-node#59]
Would it be heresy to have a secp256k1_ecdh version which doesn't hash the points?

It is easy to do in the JS part, but I understand that would mean a patch to secp256k1 upon checkout (or a suboptimal implementation). Do you think upstream secp256k1 would consider that given it is not used in Bitcoin, but Ethereum?

I would even be happy with having that only available in the JS version, but that might hurt the integrity of the API.

**Comment by wanderer** [comment]
Its general not safe to use unhashed version of ecdh. Because I think the result isn't by itself uniformly random. So it might not be something would want to expose in a public api

**Comment by fanatid** [comment]
It's not available right now, but can be if https://github.com/bitcoin/secp256k1/pull/354 or something like this will be included in [bitcoin/secp256k1](https://github.com/bitcoin/secp256k1).

**Comment by axic** [comment]
Looks good!

If that's merged upstream, would you include the hash method for Ethereum in here too? Which is this: https://github.com/ethereumjs/node-devp2p/blob/master/lib/ecies.js#L52-L71

Or would you just provide an alternative JS binding (slow) for the hash, e.g. to be defined freely in JS?

**Comment by axic** [comment]
@fanatid was there any progress in secp256k1 regarding this issue?

**Comment by fanatid** [comment]
@axic nope :(

**Comment by axic** [comment]
@fanatid if I understand it correctly, the method `ecdh` is really just `publicKeyTweakMul` + sha256 with one important difference is that `ecdh` is constant time.

**Comment by fanatid** [comment]
@axic yes, `publicKeyTweakMul` is same, but why only `ecdh` has constant time?

**Comment by fanatid** [comment]
Instead waiting while `bitcoin/secp256k1` implement new `ecdh` interface with callback/unsafe function, we could write create two functions:
- `ecdh`: current ecdh function from `bitcoin/secp256k1` (`sha256(publicKey * tweak)`)
- `ecdhUnsafe`: based on `publicKeyTweakMul` (`publicKey * tweak`)

Thoughts?

**Comment by axic** [comment]
Sounds good, will you add `ecdhUnsafe` to all three implementations?

> @axic yes, publicKeyTweakMul is same, but why only ecdh has constant time?

Not sure about the rest, but it is called `ecdh_constant`. I guess because ecdh is where the real risk lies, given it is an ongoing communications process.

**Comment by fanatid** [comment]
@axic I don't `ecdh_constant` nowhere

**Comment by axic** [comment]
@fanatid mixed it up with `ecmul_const` 😃

**Comment by fanatid** [comment]
Oh, I see.
`ecdh` uses `secp256k1_ecmult_const`, while `publicKeyTweakMul` uses `secp256k1_ecmult`
