### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#6]
Hi. Thanks for the great library.
Though there is one issue:
Is it principal for you to use GPL license? GPL requires that all programs which uses `secp256k1-node` **must** be licensed under GPL (or AGPL). This cause a lot of problems in Node world since BSD-like licenses is defacto standart. `libsecp256k1` is licensed under MIT itself.
Is it possible to relicense (make dual license) `secp256k1-node` to BSD-like? Thanks.

**Comment by wanderer** [comment]
how about just MIT? since libsecp256k1 is MIT too. Would that work for you?

**Comment by Kagami** [comment]
Yeap, MIT would be great.

**Comment by wanderer** [comment]
done in 91a634c3

**Comment by Kagami** [comment]
Thanks a lot!
