### ISSUE TITLE
Make compatible with Electron?

### ISSUE THREAD

**Issue by jprichardson** [cryptocoinjs/secp256k1-node#71]
I'm writing an Electron app (http://www.exodus.io/) and every module (a lot of the Ethereum modules) that use this module don't work without modification, unless I want to recompile native modules for every platform - which can be painful. So, right now, I'm just importing each package in my app and making the change from `require('secp256k1')` to `require('secp256k1/js')`.

Would you accept a PR that would do the following:

**index.js:**

``` js
try {
  module.exports = require('./bindings')
} catch () {
  module.exports = require('./js')
}
```

Thanks!

**Comment by fanatid** [comment]
It's looks reasonable and not only for electron, for example developer could install this package but got error on compilation stage (gyp file error?), with this `try-catch` package will be still usable.

**Comment by fanatid** [comment]
I will create PR tomorrow.

**Comment by axic** [comment]
@jprichardson are you not using browserify?

**Comment by jprichardson** [comment]
@axic I am using Browserify - but only to bundle my code together, not dependencies. So `package.json` and the `browser` field wouldn't work. But when I open source Exodus, I will not be using Browserify at all.
