### ISSUE TITLE
CI for windows

### ISSUE THREAD

**Issue by fanatid** [cryptocoinjs/secp256k1-node#74]
AppVeyor support windows and x86/x64: http://www.appveyor.com/docs/build-configuration#build-matrix
Related issues: #20 #73

**Comment by wanderer** [comment]
:+1:

**Comment by fanatid** [comment]
Resolved in https://github.com/cryptocoinjs/secp256k1-node/commit/81eef8092bc881eb7aa77f8598be240ae198b036
