### ISSUE TITLE
add saucelabs

### ISSUE THREAD

**Issue by fanatid** [cryptocoinjs/secp256k1-node#78]
https://saucelabs.com/opensauce/

**Comment by fanatid** [comment]
Tried use saucelabs with [zuul](https://github.com/defunctzombie/zuul), but build fail https://travis-ci.org/cryptocoinjs/secp256k1-node/jobs/131227381 with error:

```
Error: connection refused: localtunnel.me:43326 (check your firewall settings)
```

**Comment by dcousens** [comment]
Is the idea here for the CI to run on browser platforms?

**Comment by fanatid** [comment]
Yea, as I remember, I wanted run tests in different browsers/platforms.

**Comment by fanatid** [comment]
Karma removed.
