### ISSUE TITLE
Purpose of async methods

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#8]
Hi. Sorry for the stupid question.

Could you please explain what is the purpose of asynchronous version of methods like `sign` and `verify`? Isn't this operations supposed to be very fast so it's almost no profit in spawning additional thread for this?

**Comment by wanderer** [comment]
right, I think there is little benefit to using async.I should benchmark that though. I wrote async functions originally because I copied the API that bitcore's secp256k1 was using.

**Comment by Kagami** [comment]
Ok, thanks.
