### ISSUE TITLE
Import signatures that don't followed by bip66 rules

### ISSUE THREAD

**Issue by fanatid** [cryptocoinjs/secp256k1-node#83]
Ref: <s>https://github.com/bitcoin/secp256k1/blob/master/contrib/lax_der_privatekey_parsing.h</s>
[lax_der_parsing.h](https://github.com/bitcoin-core/secp256k1/blob/7b549b1abc06fe1c640014603346b85c8bc83e0b/contrib/lax_der_parsing.h)

**Comment by fanatid** [comment]
without this #70 can not be solved

**Comment by axic** [comment]
Can this be added then? Is it a public interface in secp256k1?

I suggest adding a flag for strict mode (default on): `signatureImport(<sig>, [strict])`

**Comment by fanatid** [comment]
yes, `bitcoin-core/secp256k1` has public interface [ecdsa_signature_parse_der_lax(ctx, sig, input, inputlen)](https://github.com/bitcoin-core/secp256k1/blob/7b549b1abc06fe1c640014603346b85c8bc83e0b/contrib/lax_der_parsing.h#L80)
I planned add separate function, but strict flag looks better.

**Comment by axic** [comment]
Alternatively it could be called "OpenSSL-mode" 😃

**Comment by dcousens** [comment]
@fanatid imho the strict function is better over a flag.

**Comment by fanatid** [comment]
@dcousens `signatureImport` / `signatureImportUnstrict` ?

**Comment by dcousens** [comment]
`signatureImportLax` if you want to be ~~more consistent~~ less original

**Comment by fanatid** [comment]
sounds reasonable
