### ISSUE TITLE
[win] libeay32.lib absolute path (LNK1181 error solved)

### ISSUE THREAD

**Issue by drandreaskrueger** [cryptocoinjs/secp256k1-node#92]
Please see [LNK1181](https://github.com/drandreaskrueger/solidity-repl/blob/master/README-win64.md#openssl) solution.

I have linked the two lines in binding.gyp

Is it the only way to demand that one specific absolute path to that library?  
If yes, then please also check the folder above, then this copying-to-lib doesn't need to be.

Alternatively, perhaps you could simply include and ship that "[libeay32.lib](https://github.com/openssl/openssl/blob/master/LICENSE)" ?

**Comment by KrishnaPG** [comment]
+1 this should be addressed properly.

**Comment by fanatid** [comment]
I added some notes about windows: https://github.com/cryptocoinjs/secp256k1-node/tree/d96965d40369a70ac255413b4f9474dc4ea7ffa4#windows

**Comment by drandreaskrueger** [comment]
Thx. I suggest you link to this workaround too, because it contains an exact description what to do (just installing it is NOT enough):
https://github.com/drandreaskrueger/solidity-repl/blob/master/README-win64.md#openssl

**Comment by fanatid** [comment]
@drandreaskrueger why installing OpenSSL is NOT enough?

**Comment by drandreaskrueger** [comment]
it also needed

```
mkdir lib
copy libeay32.lib lib
```

**Comment by fanatid** [comment]
@drandreaskrueger check new version of OpenSSL (1.0.2h for example)

**Comment by drandreaskrueger** [comment]
If that does fix it, fine. 

My own problem was [solved](https://github.com/drandreaskrueger/solidity-repl/blob/master/README-win64.md#openssl), anyways, in June already.

Thanks for your efforts. Have a nice day.
