### ISSUE TITLE
Allow bindings fail?

### ISSUE THREAD

**Issue by fanatid** [cryptocoinjs/secp256k1-node#94]
Since we have pure JS implementation we can allow compilation fail (of course speed will be much less).

``` json
{
  ..
  "scripts": {
    ..
    "install": "npm run rebuild || echo \"Bindings compile fail. Pure JS implementation will be used\""
  }
}
```

but I not sure that this will work on windows..

**Comment by jprichardson** [comment]
I think this is great - as in the case with Exodus, at this moment, I prefer to not use native bindings at all.
