### ISSUE TITLE
Schnorr signatures

### ISSUE THREAD

**Issue by chjj** [cryptocoinjs/secp256k1-node#97]
Any thoughts on exposing the schnorr module from secp256k1? Schnorr signatures are no doubt going to be in bitcoin's future at some point.

I've [implemented the schnorr module in javascript](https://github.com/bcoin-org/bcoin/blob/master/lib/crypto/schnorr.js). It's correct as far as I can guess, but it still needs more tests to ensure it's accurate to the libsecp256k1 implementation. I could rip it out of bcoin and move it to secp256k1-node for the browser-side compat.

**Comment by fanatid** [comment]
@chjj I would like add Schnorr signatures to secp256k1, but shouldn't we add this type of signatures to http://github.com/indutny/elliptic first? ping @indutny

**Comment by chjj** [comment]
Yeah, I was wondering if Fedor would want them there. It looks like the libsecp256k1 implementation of Schnorr sigs deviates from what's considered standard (for example, the hashing is different from other implementations I've seen). cc @indutny

**Comment by indutny** [comment]
I think it would be a better choice to publish Schnorr signatures as a separate package with dependency on elliptic.

**Comment by fanatid** [comment]
@chjj original code of `bitcoin-core/secp256k1` doesn't contain [restored public key check](https://github.com/bcoin-org/bcoin/blob/fbb7f25d0a310c5d8a44bfc4dcc7f44ecf5648c6/lib/crypto/schnorr.js#L196-L204)
It is really necessary for us?

**Comment by chjj** [comment]
@fanatid, yeah, I'm not sure. I noticed the btcd implementation didn't include it either, but I decided to add it for good measure since the hash is already computed. I'm not sure if it's actually necessary though.

**Comment by fanatid** [comment]
https://github.com/bitcoin-core/secp256k1/pull/416#issuecomment-256683582
Should be reopened when schnorr will be ready.
